Чейнжлоги в дис!
AdventureTimeSS14/Dev-bot pull request #16
Opened 2024-08-29 22:23 UTC by Schrodinger71

Теперь чейнжлоги замердженных пров основной репы будут поститься в дис, в определённый канал
![image](https://github.com/user-attachments/assets/870fe65a-076e-4271-9189-769ac0576a2f)

2024-08-30 12:07 UTC, nixsilvam404 requested changes
work

2024-08-30 12:07 UTC, nixsilvam404 commented on events/on_ready.py
> +    bot.loop.create_task(fetch_merged_pull_requests())
поменять местами с 6 строкой

2024-08-30 12:07 UTC, nixsilvam404 commented on commands/github/git_fetch_pull.py
> +        await asyncio.sleep(60)  # Проверять каждую минуту
60 вынести в конфиг

2024-08-30 12:07 UTC, nixsilvam404 commented on commands/github/git_fetch_pull.py
> +async def fetch_merged_pull_requests():
используй `@tasks.loop`
вместо asyncio

2024-08-30 12:09 UTC, Schrodinger71 commented on commands/github/git_fetch_pull.py
> +async def fetch_merged_pull_requests():
что за жесть

2024-08-30 12:09 UTC, Schrodinger71 commented on commands/github/git_fetch_pull.py
> +async def fetch_merged_pull_requests():
это как

2024-08-30 12:10 UTC, Schrodinger71 commented on commands/github/git_fetch_pull.py
> +                            embed.add_field(name='Изменения:', value=description, inline=False)
ну у нас ни разу превышали изменения больше 10 строк в чейнжлоге

2024-08-30 12:10 UTC, Schrodinger71 commented on commands/github/git_fetch_pull.py
> +        if response.status_code == 200:
в плане инвертировать?

2024-08-30 12:17 UTC, nixsilvam404 commented on commands/github/git_fetch_pull.py
> +        await asyncio.sleep(60)  # Проверять каждую минуту
через task.loop эта проблема решится сама

2024-08-30 12:37 UTC, Schrodinger71 commented on events/on_ready.py
> +    bot.loop.create_task(fetch_merged_pull_requests())
Поменял

2024-08-30 12:39 UTC, Schrodinger71 commented on commands/github/git_fetch_pull.py
> +REPO = 'AdventureTimeSS14/space_station_ADT'
Готово

2024-08-30 12:41 UTC, nixsilvam404 commented on commands/github/git_fetch_pull.py
> +        if response.status_code == 200:
сделай сначала через task.loop всё
а так сделать  наоборот, через 
```py
if not smth:
   Отправляет ошибку
```
и дальше код

этот обычный if делает слишком огромное каскадное условие, кооторого можно избежать

2024-08-30 12:41 UTC, Schrodinger71 commented on commands/github/git_fetch_pull.py
> +from .github_processor import (create_embed_list, fetch_github_data,
Убрал

2024-08-30 12:42 UTC, Schrodinger71 commented on commands/github/git_fetch_pull.py
> +    last_checked_time = datetime.utcnow()  # Время последней проверки
gg

2024-08-30 12:47 UTC, Schrodinger71 commented on commands/github/git_fetch_pull.py
> +                        description = pr['body'] if pr['body'] else "Нет описания"
Yees

2024-09-01 15:38 UTC, nixsilvam404 approved these changes

2024-09-01 15:41 UTC, merged